apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "postgres-gcs-backup.fullname" . }}
  labels:
    app: {{ template "postgres-gcs-backup.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  schedule: {{ .Values.schedule }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          name: {{ template "postgres-gcs-backup.fullname" . }}
          labels:
            app: {{ .Release.Name }}
            cron: {{ template "postgres-gcs-backup.name" . }}
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
{{ toYaml .Values.env | indent 12 }}
            volumeMounts:
              - name: gcp-credentials
                mountPath: /secrets/gcp
                readOnly: true
            resources:
  {{ toYaml .Values.resources | indent 12 }}
          restartPolicy: {{ .Values.restartPolicy }}
          volumes:
            - name: gcp-credentials
              secret:
                secretName: {{ .Values.gcsCredentials.secret.name }}
                items:
                - key: {{ .Values.gcsCredentials.secret.key }} 
                  path: "gcs-creds.json"
