name: Build and Push Docker Image

on:
  push:
    tags: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_DOCKER_REGISTRY }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/postgres-gcs-backup:${{ github.ref_name }}
            ${{ secrets.DOCKERHUB_USERNAME }}/postgres-gcs-backup:latest
            ghcr.io/${{ github.repository_owner }}/postgres-gcs-backup:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/postgres-gcs-backup:latest

      - name: Image digest
        run: echo "Image digest is ${{ steps.build.outputs.digest }}"
